/*
 * Hochschulstart Mock-API
 * An API-Spec used for hochschulstart as first try.
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package it.eng.opsi.service.connector.service.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;


/**
 * Application
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-05-05T16:06:27.017901400+02:00[Europe/Rome]")public class Application {

  @JsonProperty("id")

  private Integer id = null;

  @JsonProperty("semester")

  private String semester = null;

  @JsonProperty("institution")

  private String institution = null;

  @JsonProperty("course")

  private String course = null;

  @JsonProperty("admissionPeriodFrom")

  private String admissionPeriodFrom = null;

  @JsonProperty("admissionPeriodTo")

  private String admissionPeriodTo = null;

  @JsonProperty("period")

  private String period = null;
  public Application id(Integer id) {
    this.id = id;
    return this;
  }

  

  /**
  * Get id
  * @return id
  **/
  @Schema(description = "")
  public Integer getId() {
    return id;
  }
  public void setId(Integer id) {
    this.id = id;
  }
  public Application semester(String semester) {
    this.semester = semester;
    return this;
  }

  

  /**
  * Get semester
  * @return semester
  **/
  @Schema(description = "")
  public String getSemester() {
    return semester;
  }
  public void setSemester(String semester) {
    this.semester = semester;
  }
  public Application institution(String institution) {
    this.institution = institution;
    return this;
  }

  

  /**
  * Get institution
  * @return institution
  **/
  @Schema(description = "")
  public String getInstitution() {
    return institution;
  }
  public void setInstitution(String institution) {
    this.institution = institution;
  }
  public Application course(String course) {
    this.course = course;
    return this;
  }

  

  /**
  * Get course
  * @return course
  **/
  @Schema(description = "")
  public String getCourse() {
    return course;
  }
  public void setCourse(String course) {
    this.course = course;
  }
  public Application admissionPeriodFrom(String admissionPeriodFrom) {
    this.admissionPeriodFrom = admissionPeriodFrom;
    return this;
  }

  

  /**
  * Get admissionPeriodFrom
  * @return admissionPeriodFrom
  **/
  @Schema(description = "")
  public String getAdmissionPeriodFrom() {
    return admissionPeriodFrom;
  }
  public void setAdmissionPeriodFrom(String admissionPeriodFrom) {
    this.admissionPeriodFrom = admissionPeriodFrom;
  }
  public Application admissionPeriodTo(String admissionPeriodTo) {
    this.admissionPeriodTo = admissionPeriodTo;
    return this;
  }

  

  /**
  * Get admissionPeriodTo
  * @return admissionPeriodTo
  **/
  @Schema(description = "")
  public String getAdmissionPeriodTo() {
    return admissionPeriodTo;
  }
  public void setAdmissionPeriodTo(String admissionPeriodTo) {
    this.admissionPeriodTo = admissionPeriodTo;
  }
  public Application period(String period) {
    this.period = period;
    return this;
  }

  

  /**
  * Get period
  * @return period
  **/
  @Schema(description = "")
  public String getPeriod() {
    return period;
  }
  public void setPeriod(String period) {
    this.period = period;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Application application = (Application) o;
    return Objects.equals(this.id, application.id) &&
        Objects.equals(this.semester, application.semester) &&
        Objects.equals(this.institution, application.institution) &&
        Objects.equals(this.course, application.course) &&
        Objects.equals(this.admissionPeriodFrom, application.admissionPeriodFrom) &&
        Objects.equals(this.admissionPeriodTo, application.admissionPeriodTo) &&
        Objects.equals(this.period, application.period);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(id, semester, institution, course, admissionPeriodFrom, admissionPeriodTo, period);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Application {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    semester: ").append(toIndentedString(semester)).append("\n");
    sb.append("    institution: ").append(toIndentedString(institution)).append("\n");
    sb.append("    course: ").append(toIndentedString(course)).append("\n");
    sb.append("    admissionPeriodFrom: ").append(toIndentedString(admissionPeriodFrom)).append("\n");
    sb.append("    admissionPeriodTo: ").append(toIndentedString(admissionPeriodTo)).append("\n");
    sb.append("    period: ").append(toIndentedString(period)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
