/*
 * Hochschulstart Mock-API
 * An API-Spec used for hochschulstart as first try.
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package it.eng.opsi.service.connector.service.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;


/**
 * Status
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-05-05T16:06:27.017901400+02:00[Europe/Rome]")public class Status {

  @JsonProperty("id")

  private Integer id = null;

  @JsonProperty("level")

  private String level = null;

  @JsonProperty("note")

  private String note = null;

  @JsonProperty("pointOfEntry")

  private String pointOfEntry = null;

  @JsonProperty("modified")

  private String modified = null;

  @JsonProperty("created")

  private String created = null;
  public Status id(Integer id) {
    this.id = id;
    return this;
  }

  

  /**
  * Get id
  * @return id
  **/
  @Schema(description = "")
  public Integer getId() {
    return id;
  }
  public void setId(Integer id) {
    this.id = id;
  }
  public Status level(String level) {
    this.level = level;
    return this;
  }

  

  /**
  * Get level
  * @return level
  **/
  @Schema(description = "")
  public String getLevel() {
    return level;
  }
  public void setLevel(String level) {
    this.level = level;
  }
  public Status note(String note) {
    this.note = note;
    return this;
  }

  

  /**
  * Get note
  * @return note
  **/
  @Schema(description = "")
  public String getNote() {
    return note;
  }
  public void setNote(String note) {
    this.note = note;
  }
  public Status pointOfEntry(String pointOfEntry) {
    this.pointOfEntry = pointOfEntry;
    return this;
  }

  

  /**
  * Get pointOfEntry
  * @return pointOfEntry
  **/
  @Schema(description = "")
  public String getPointOfEntry() {
    return pointOfEntry;
  }
  public void setPointOfEntry(String pointOfEntry) {
    this.pointOfEntry = pointOfEntry;
  }
  public Status modified(String modified) {
    this.modified = modified;
    return this;
  }

  

  /**
  * Get modified
  * @return modified
  **/
  @Schema(description = "")
  public String getModified() {
    return modified;
  }
  public void setModified(String modified) {
    this.modified = modified;
  }
  public Status created(String created) {
    this.created = created;
    return this;
  }

  

  /**
  * Get created
  * @return created
  **/
  @Schema(description = "")
  public String getCreated() {
    return created;
  }
  public void setCreated(String created) {
    this.created = created;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Status status = (Status) o;
    return Objects.equals(this.id, status.id) &&
        Objects.equals(this.level, status.level) &&
        Objects.equals(this.note, status.note) &&
        Objects.equals(this.pointOfEntry, status.pointOfEntry) &&
        Objects.equals(this.modified, status.modified) &&
        Objects.equals(this.created, status.created);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(id, level, note, pointOfEntry, modified, created);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Status {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    level: ").append(toIndentedString(level)).append("\n");
    sb.append("    note: ").append(toIndentedString(note)).append("\n");
    sb.append("    pointOfEntry: ").append(toIndentedString(pointOfEntry)).append("\n");
    sb.append("    modified: ").append(toIndentedString(modified)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
